/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoli_llvmir_generator_LLVMIRGenerator */

#ifndef _Included_com_xiaoli_llvmir_generator_LLVMIRGenerator
#define _Included_com_xiaoli_llvmir_generator_LLVMIRGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator
 * Method:    createLLVMContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_createLLVMContext
  (JNIEnv *, jclass);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator
 * Method:    createLLVMModule
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_createLLVMModule
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator
 * Method:    createLLVMBuilder
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_createLLVMBuilder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator
 * Method:    destroyLLVMContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_destroyLLVMContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator
 * Method:    destroyLLVMModule
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_destroyLLVMModule
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator
 * Method:    destroyLLVMBuilder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_destroyLLVMBuilder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator
 * Method:    dumpLLVMModule
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_dumpLLVMModule
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
