/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator */

#ifndef _Included_com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
#define _Included_com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitFunction
 * Signature: (Lldk/l/lg/ir/base/IRFunction;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitFunction
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitReturn
 * Signature: (Lldk/l/lg/ir/instruction/IRReturn;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitReturn
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitGoto
 * Signature: (Lldk/l/lg/ir/instruction/IRGoto;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitGoto
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitConditionalJump
 * Signature: (Lldk/l/lg/ir/instruction/IRConditionalJump;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitConditionalJump
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitCalculate
 * Signature: (Lldk/l/lg/ir/instruction/IRCalculate;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitCalculate
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitNot
 * Signature: (Lldk/l/lg/ir/instruction/IRNot;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitNot
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitNegate
 * Signature: (Lldk/l/lg/ir/instruction/IRNegate;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitNegate
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitIncrease
 * Signature: (Lldk/l/lg/ir/instruction/IRIncrease;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitIncrease
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitDecrease
 * Signature: (Lldk/l/lg/ir/instruction/IRDecrease;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitDecrease
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitSet
 * Signature: (Lldk/l/lg/ir/instruction/IRSet;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitSet
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitGet
 * Signature: (Lldk/l/lg/ir/instruction/IRGet;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitGet
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitStackAllocate
 * Signature: (Lldk/l/lg/ir/instruction/IRStackAllocate;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitStackAllocate
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitSetVirtualRegister
 * Signature: (Lldk/l/lg/ir/instruction/IRSetVirtualRegister;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitSetVirtualRegister
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitAsm
 * Signature: (Lldk/l/lg/ir/instruction/IRAsm;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitAsm
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitConstant
 * Signature: (Lldk/l/lg/ir/operand/IRConstant;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitConstant
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitVirtualRegister
 * Signature: (Lldk/l/lg/ir/operand/IRVirtualRegister;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitVirtualRegister
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_xiaoli_llvmir_generator_LLVMIRGenerator_LLVMModuleGenerator
 * Method:    visitMacro
 * Signature: (Lldk/l/lg/ir/operand/IRMacro;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoli_llvmir_1generator_LLVMIRGenerator_00024LLVMModuleGenerator_visitMacro
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
